# Alternating Sort
'''
 You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:
 - b[0] is equal to a[0]
 - b[1] is equal to the last element of a
 - b[2] is equal to a[1]
 - b[3] is equal to the second to last element of a
 - and so on

 Your task is to determine whether the new array b is sorted in strictly ascending order or not. 

 Example:
 - For a = [1,3,5,6,4,2], the output should be alternatingSort(a) = True
 The new array b will look like [1,2,3,4,5,6] which is in strictly ascending order so the answer is true
 - For a = [1,4,5,6,3], the output should be alternatingSort(a) = False
 The new array b will look like [1,3,4,6,5] which is not in strictly ascending order so the answer is false 
'''

def AltSort(a):
    b = []

    for i in range(len(a)):
        if i % 2 == 0:
            b.append(a[i // 2])
            if i > 0 and b[i] <= b[i - 1]:
                return False
        else:
            b.append(a[(i + 1) // -2])
            if b[i] <= b[i - 1]:
                return False
    return True

# a = [1, 1, 1, 1, 1, 1]
# a = [1, 3, 5, 6, 4, 2]
# a = [1, 4, 5, 6, 3]
# a = [1, 5, 9, 20, 40, 69, 25, 15, 7, 3]

a = [1, 5, 9, 20, 40, 69, 25, 15, 3, 7]
print(AltSort(a))